# Generated by Django 5.1.6 on 2025-04-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_categorys_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
