# Generated by Django 5.1.6 on 2025-04-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_categorys_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
