# Generated by Django 5.1.6 on 2025-04-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='products/')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('Link', models.CharField(max_length=255)),
                ('File', models.FileField(upload_to='')),
                ('isActive', models.BooleanField(default=True)),
                ('By', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='store.categorys')),
            ],
        ),
    ]
