# Generated by Django 5.1.6 on 2025-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=99999)),
                ('email', models.CharField(max_length=600)),
                ('number', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='')),
                ('prto', models.CharField(max_length=255)),
                ('Eyear', models.IntegerField()),
                ('Emonth', models.IntegerField()),
                ('Eday', models.IntegerField()),
                ('Syear', models.IntegerField()),
                ('Smonth', models.IntegerField()),
                ('Sday', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
