# Generated by Django 5.1.6 on 2025-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cobon',
            field=models.CharField(max_length=25),
        ),
    ]
