# Generated by Django 5.1.6 on 2025-03-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanal', '0002_alter_task_cobon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cobon',
        ),
    ]
