# Generated by Django 5.1.5 on 2025-02-25 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('duration', models.IntegerField(max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('By', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('Done', models.BooleanField(default=False)),
                ('Cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson', to='CourcePanal.cource')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Done', models.BooleanField(default=False)),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to='CourcePanal.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.CharField(max_length=2000)),
                ('answer1', models.CharField(max_length=2000)),
                ('answer2', models.CharField(max_length=2000)),
                ('answer3', models.CharField(max_length=2000)),
                ('TrueAnswer', models.CharField(max_length=2000)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Q', to='CourcePanal.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_Name', models.CharField(max_length=255)),
                ('Done', models.BooleanField(default=False)),
                ('Cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscribe', to='CourcePanal.cource')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscribe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
