# Generated by Django 5.1.5 on 2025-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
