# Generated by Django 5.1.5 on 2025-02-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0002_alter_cource_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='image',
            field=models.ImageField(default='default.png', upload_to='courses/'),
        ),
    ]
