# Generated by Django 5.1.5 on 2025-02-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0004_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='Cource',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='Cource',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Lesson',
        ),
        migrations.RemoveField(
            model_name='q',
            name='Exam',
        ),
        migrations.DeleteModel(
            name='lang',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='User',
        ),
        migrations.DeleteModel(
            name='Cource',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Q',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
