# Generated by Django 5.1.5 on 2025-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q',
            name='Exam',
        ),
        migrations.AlterField(
            model_name='cource',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Q',
        ),
    ]
