# Generated by Django 5.1.5 on 2025-02-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0007_remove_q_exam_alter_cource_description_delete_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Done', models.BooleanField(default=False)),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to='CourcePanal.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.CharField(max_length=2000)),
                ('answer1', models.CharField(max_length=2000)),
                ('answer2', models.CharField(max_length=2000)),
                ('answer3', models.CharField(max_length=2000)),
                ('TrueAnswer', models.CharField(max_length=2000)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Q', to='CourcePanal.exam')),
            ],
        ),
    ]
