# Generated by Django 5.1.5 on 2025-02-27 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0010_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Done_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Done_Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoneLessons', to='CourcePanal.lesson')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoneLessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
