# Generated by Django 5.1.5 on 2025-03-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0014_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
