# Generated by Django 5.1.5 on 2025-03-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0019_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='Cource',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='Cource',
        ),
        migrations.RemoveField(
            model_name='done_lessons',
            name='Done_Lesson',
        ),
        migrations.RemoveField(
            model_name='done_lessons',
            name='User',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Lesson',
        ),
        migrations.RemoveField(
            model_name='q',
            name='Exam',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='User',
        ),
        migrations.DeleteModel(
            name='lang',
        ),
        migrations.DeleteModel(
            name='Cource',
        ),
        migrations.DeleteModel(
            name='Done_Lessons',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Q',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
