# Generated by Django 5.1.5 on 2025-03-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0021_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Done_Lessons',
        ),
    ]
