# Generated by Django 5.1.5 on 2025-03-02 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0023_done_lessons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='done_lessons',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='completion_date',
        ),
        migrations.AlterField(
            model_name='done_lessons',
            name='Done_Lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoneLessons', to='CourcePanal.lesson'),
        ),
        migrations.AlterField(
            model_name='done_lessons',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoneLessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='done_lessons',
            name='created_at',
        ),
    ]
