# Generated by Django 5.1.5 on 2025-03-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourcePanal', '0025_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
